
(let ((result (instantiate '(:Q :E :Q))))
  (and (cons? result)
       (let ((r2 (car result))
             (r3 (car (cdr result)))
             (r4 (car (cdr (cdr result)))))
         (and (keyword? r2)
              (keyword? r3)
              (keyword? r4)
              (eq? r2 r4)
              (not (eq? r2 r3))
              (not (eq? :Q r2))
              (not (eq? :E r3))))))
